empty_cart_message_loc = '.js_cart_lines'
review_order_loc = '.d-md-flex:nth-child(1)'
shipping_loc = '.d-md-flex:nth-child(2)'
payment_loc = '.d-md-flex:nth-child(3)'
list_of_remove_one_button_loc = '[aria-label="Remove one"]'
list_of_add_one_button_loc = '[aria-label="Add one"]'
list_value_of_product_loc = '.js_quantity'
list_of_product_prices_loc = '[data-oe-expression="product_price"] span'
subtotal_price_loc = '#order_total_untaxed span span'
