terms_and_conditions_loc = '#o_product_terms_and_share p a'
icon_of_facebook = '[aria-label="Facebook"]'
page_title = '#product_details > h1'
plus_button_loc = '[aria-label="Add one"]'
add_to_cart_button_loc = '#add_to_cart'
product_price_loc = '.oe_price span'
selector_of_currency_loc = '.o_pricelist_dropdown > a'
eur_currency_loc = '.o_pricelist_dropdown div a:nth-child(2)'
price_currency_loc = '[itemprop="priceCurrency"]'
